FROM ubuntu:22.04 AS build

WORKDIR /app

RUN apt-get update && apt-get install -y \
    g++ \
    libcpprest-dev \
    libboost-all-dev \
    libssl-dev \
    libspdlog-dev \
    libfmt-dev \
    cmake \
    libgtest-dev

COPY *.cpp *.hpp ./
COPY ./features/ ./features/


### Builder
RUN g++ -std=c++20 -c ./features/logger/logger.cpp -o ./features/logger.o
RUN g++ -std=c++20 -c ./features/tokenizer/tokenizer.cpp -o ./features/tokenizer.o
RUN g++ -std=c++20 -c ./features/scoreEngine/scoreEngine.cpp -o ./features/scoreEngine.o
RUN g++ -std=c++20 -c ./features/drawer/drawer.cpp -o ./features/drawer.o
RUN g++ -std=c++20 -c ./features/controllers/syncController.cpp -o ./features/syncController.o
RUN g++ -std=c++20 -c ./features/controllers/questionController.cpp -o ./features/questionController.o
RUN g++ -std=c++20 -c ./features/api/api.cpp -o ./features/api.o 
RUN g++ -std=c++20 -o endless endless.cpp \
    ./features/api.o \
    ./features/logger.o \
    ./features/tokenizer.o \
    ./features/scoreEngine.o \
    ./features/drawer.o \
    ./features/syncController.o \
    ./features/questionController.o \
    -lcpprest -lboost_system -lboost_thread -lboost_chrono -lboost_random -lssl -lcrypto -lspdlog -lfmt

### Tests
RUN g++ -std=c++20 -o run_tests \
    ./testFeatures.cpp \
    ./features/scoreEngine/scoreEngine.test.cpp \
    ./features/tokenizer/tokenizer.test.cpp \
    ./features/scoreEngine.o \
    ./features/tokenizer.o \
    ./features/logger.o \
    -lgtest -lgtest_main -pthread \
    -lcpprest -lboost_system -lboost_thread -lboost_chrono -lboost_random -lssl -lcrypto \
    -lspdlog -lfmt

RUN ./run_tests

### Runner
FROM ubuntu:22.04
WORKDIR /app
RUN apt-get update && apt-get install -y \
    libcpprest2.10 \
    libboost-system1.74.0 \
    libboost-thread1.74.0 \
    libboost-chrono1.74.0 \
    libboost-random1.74.0 \
    libssl3 \
    libfmt8 \
    libspdlog1 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=build /app/endless .

EXPOSE 8080

CMD ["./endless"]
